### PR TITLE
adds writeBaseString failing test

### PR DESCRIPTION
**Pull request by adam-hanna**
Have I done something wrong with this test?

```bash
$ go test ./oauth/ -v -run=TestWriteBaseSting
=== RUN   TestWriteBaseSting
=== RUN   TestWriteBaseSting/0
    oauth_test.go:72: url string https://www.interactivebrokers.com/tradingapi/v1/oauth/request_token
    oauth_test.go:77: expected POST&https%3A%2F%2Fwww.interactivebrokers.com%2Ftradingapi%2Fv1%2Foauth%2Frequest_token, received POST&https%3A%2F%2Fwww.interactivebrokers.comtradingapi%2Fv1%2Foauth%2Frequest_token&
--- FAIL: TestWriteBaseSting (0.00s)
    --- FAIL: TestWriteBaseSting/0 (0.00s)
FAIL
FAIL    github.com/gomodule/oauth1/oauth        0.003s
FAIL
```

### CODE REVIEW

**Comment by garyburd** [comment]
> Have I done something wrong with this test?

The test constructs a URL with an invalid request URI.  Garbage in,  garbage out.

**Comment by adam-hanna** [comment]
> > Have I done something wrong with this test?
> 
> The test constructs a URL with an invalid request URI. Garbage in, garbage out.

Check the log I included. The url is valid.

**Comment by adam-hanna** [comment]
Added another test case to show my point.

**Comment by garyburd** [comment]
Update the issue with a description of the problem you encountered using the exported API for the package. 

The result of URL.String() is not relevant.  The URL.Path field in the first test is not absolute.

The expected strings in both tests are missing the trailing `&`.

**Comment by adam-hanna** [comment]
It's shown in the test

**Comment by adam-hanna** [comment]
It's not a trailing &, it's missing a `/` between the path and host as pointed out in the issue

**Comment by garyburd** [comment]
Closed per [comment in related issue](https://github.com/gomodule/oauth1/issues/46#issuecomment-1017898437).

**Pull request closed without merging**
